# This is a basic workflow to help you get started with Actions

name: LilyPond Render Music

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install LilyPond
        run: sudo apt-get install lilypond

      - name: Compile LilyPond
        working-directory: ${{ github.workspace }}
        run: |
          pwd
          mkdir generated_files
          find . -type f -name "*.ly" -print0 | while IFS= read -r -d '' file; do 
            lilypond -o generated_files "$file"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LilyPond Files
          path: $GITHUB_WORKSPACE/generated_files
